export const  enumTags = [
    ["python" , "Python"],
    ["javascript" , "JavaScript"],
    ["java" , "Java"],
    ["csharp" , "C#"],
    ["cpp" , "C++"],
    ["php" , "PHP"],
    ["ruby" , "Ruby"],
    ["swift" , "Swift"],
    ["go" , "Go"],
    ["rust" , "Rust"],
    ["kotlin" , "Kotlin"],
    ["typescript" , "TypeScript"],
    ["html" , "HTML"],
    ["css" , "CSS"],
    ["sql", "SQL"],
    ["r" , "R"],
    ["matlab" , "MATLAB"],
    ["bash" , "Bash"],
    ["perl" , "Perl"],
    ["html5" , "HTML5"],
    ["css3" , "CSS3"],
    ["react" , "React"],
    ["angular" , "Angular"],
    ["vuejs" , "Vue.js"],
    ["svelte" , "Svelte"],
    ["nodejs" , "Node.js"],
    ["django" , "Django"],
    ["flask" , "Flask"],
    ["rubyonrails" , "Ruby on Rails"],
    ["aspnet" , "ASP.NET"],
    ["laravel" , "Laravel"],
]
