"""empty message

Revision ID: 861f693595f8
Revises: c1e540b4734c
Create Date: 2024-06-28 13:59:48.466584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861f693595f8'
down_revision = 'c1e540b4734c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_primary', sa.Boolean(), nullable=False))
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('is_primary')

    # ### end Alembic commands ###
