"""empty message

Revision ID: f137ed69fc02
Revises: 861f693595f8
Create Date: 2024-06-29 13:18:28.449902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f137ed69fc02'
down_revision = '861f693595f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('tag',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('python', 'javascript', 'java', 'csharp', 'cpp', 'php', 'ruby', 'swift', 'go', 'rust', 'kotlin', 'typescript', 'html', 'css', 'sql', 'r', 'matlab', 'bash', 'perl', 'html5', 'css3', 'react', 'angular', 'vuejs', 'svelte', 'nodejs', 'django', 'flask', 'rubyonrails', 'aspnet', 'laravel', 'expressjs', 'graphql', 'restful_apis', 'bootstrap', 'tailwind_css', 'android', 'ios', 'react_native', 'flutter', 'xamarin', 'swiftui', 'kotlin_multiplatform', 'mysql', 'postgresql', 'mongodb', 'sqlite', 'redis', 'oracle', 'sql_server', 'firebase', 'dynamodb', 'aws', 'azure', 'google_cloud', 'docker', 'kubernetes', 'jenkins', 'ansible', 'terraform', 'ci_cd', 'gitlab', 'github_actions', 'git', 'github', 'bitbucket', 'vscode', 'intellij_idea', 'pycharm', 'sublime_text', 'eclipse', 'netbeans', 'agile', 'scrum', 'kanban', 'unit_testing', 'integration_testing', 'tdd', 'bdd', 'continuous_integration', 'continuous_deployment', 'algorithms', 'data_structures', 'machine_learning', 'deep_learning', 'artificial_intelligence', 'data_science', 'big_data', 'cybersecurity', 'blockchain', 'internet_of_things', 'game_development', 'virtual_reality', 'augmented_reality', 'robotics', 'api_design', 'software_architecture', 'microservices', 'performance_optimization', 'code_review', 'pair_programming', name='tags'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('tag',
               existing_type=sa.Enum('python', 'javascript', 'java', 'csharp', 'cpp', 'php', 'ruby', 'swift', 'go', 'rust', 'kotlin', 'typescript', 'html', 'css', 'sql', 'r', 'matlab', 'bash', 'perl', 'html5', 'css3', 'react', 'angular', 'vuejs', 'svelte', 'nodejs', 'django', 'flask', 'rubyonrails', 'aspnet', 'laravel', 'expressjs', 'graphql', 'restful_apis', 'bootstrap', 'tailwind_css', 'android', 'ios', 'react_native', 'flutter', 'xamarin', 'swiftui', 'kotlin_multiplatform', 'mysql', 'postgresql', 'mongodb', 'sqlite', 'redis', 'oracle', 'sql_server', 'firebase', 'dynamodb', 'aws', 'azure', 'google_cloud', 'docker', 'kubernetes', 'jenkins', 'ansible', 'terraform', 'ci_cd', 'gitlab', 'github_actions', 'git', 'github', 'bitbucket', 'vscode', 'intellij_idea', 'pycharm', 'sublime_text', 'eclipse', 'netbeans', 'agile', 'scrum', 'kanban', 'unit_testing', 'integration_testing', 'tdd', 'bdd', 'continuous_integration', 'continuous_deployment', 'algorithms', 'data_structures', 'machine_learning', 'deep_learning', 'artificial_intelligence', 'data_science', 'big_data', 'cybersecurity', 'blockchain', 'internet_of_things', 'game_development', 'virtual_reality', 'augmented_reality', 'robotics', 'api_design', 'software_architecture', 'microservices', 'performance_optimization', 'code_review', 'pair_programming', name='tags'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
